server:
   port: 9000
   
debug: false # 可以查看自动配置启用禁用了哪些配置

logging:
#    file: ./logs/slf4j-log.log
   level: 
      org.squirrel: debug
      

spring:
#    profiles:
#       include: 
#          - exclude-factories # 可以排除掉不需要的自动配置  
   datasource:
      # 使用 hikari 数据库连接池
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: ha
      url: jdbc:mysql://47.108.202.242:3306/test?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
      hikari:
         # 最小空闲连接数量
         minimum-idle: 5
         # 连接池最大连接数，默认是10
         maximum-pool-size: 30
         auto-commit: true
         # 空闲连接存活最大时间，默认600000（10分钟）单位毫秒
         idle-timeout: 18000
         pool-name: DatebookHikariCP
         # 池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
         max-lifetime: 1800000
         # 数据库连接超时时间,默认30秒，即30000
         connection-timeout: 30000
         connection-test-query: SELECT 1
#    redis: 
#       database: 0
#       host: 127.0.0.1
#       port: 6379
#       password: root
#       timeout: 200 
#       file: classpath:redisson.yml 
#       config: |
         
mybatis-plus:
   mapper-locations:
     - classpath:mapper/*.xml
   type-aliases-package: org.squirrel.test.web
   global-config:
      db-config:
        logic-delete-value: 1
        logic-not-delete-value: 0
   configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
        
mybatis:
   configuration:
      mapUnderscoreToCamelCase: true
      map-underscore-to-camel-case: true